---

- hosts: localhost
  tasks:
    - name: Install boto3
      pip:
        name: boto3
        state: present
    - name: Create s3 bucketName
      s3_bucket:
        name: wsraj-tf-12121118
        region: us-east-2
        state: present
