---
- hosts: localhost
  vars:
    state: present
    s3_bucket: wsraj-tf-12121118
    key: terraform.tfstate
    region: us-east-2
    profile: awsraj
    app_env: dev
  tasks:
    - name: Run Terraform Scripts
      terraform:
        project_path: "./"
        state: "{state}"
        backend_config:
          bucket: wsraj-tf-12121118
          key: "{key}"
          region: "{region}"
        variables_file: "{app_env}.tfvars"
        workspace: "{app_env}"
